### ISSUE TITLE
Svt has broken compatibility with play_latest

### ISSUE THREAD

**Issue by jptuomi** [lindell/home-assistant-svt-play#17]
Thank you for a great custom component it has been working really great through HACS for me the last year or however long I've used it. I've been running an automation / script for a while that starts and stops playback of Bolibompaklubben for the kids at a certain time.

However recently they changed the timing of the uploads leading to the programs without the movies going to the top, I don't know if they also do this by default for the rest of their programming it has however been happening consistently for over a week.

Anyway, I found a solution to this by looking at your code and changing index from 0 to 1 in the function declaration of video_id_by_time as the video, with the above recent changes combined with your sorting – will always end up second. I'd of course prefer to set this when calling the service instead however I'm oblivious to what would be required to get there.

home-assistant-svt-play/custom_components/svt_play/video_url_fetch/video_fetch.py line: 50
```py
def video_id_by_time(program_id, index=1, categories=None):
    "Get the video id of a video based on the time it became available"
    program_data = information_by_program_id(program_id)
```

My calling of the service if you'd like to test it:
```yaml
service: svt_play.play_latest
data:
  entity_id: media_player.shield
  program_name: bolibompaklubben
```

Edit: Don't really know what happened with the formatting above.

**Comment by lindell** [comment]
Hello and thanks for the issue.

Adding an index should be easy if that is the best solution, but I think it might not be in this case. SVT might change the order to run without the movies (I assume this is referring to movie clips within the video?).

A better solution for this case, and potentially others, would be to implement positive and negative name matching (with regexp).

So that you could set it up with something like:
```yaml
service: svt_play.play_latest
data:
  entity_id: media_player.shield
  program_name: bolibompaklubben
  skip: "Utan filmer"
```
